---
- name: Download OneAgent installer in specific version to a custom
    directory with additional OneAgent install parameters. Both linux_other
    and linux_arm have different user specified by platform args parameter.
  hosts: linux_other
  collections:
    - dynatrace.oneagent
  # credentials.yml file contains oneagent_environment_url and
  # oneagent_paas_token variables that needs to be stored securely
  vars_files:
    - credentials.yml
  vars:
    oneagent_download_dir: /var/opt
    oneagent_version: latest
    oneagent_install_args:
      - INSTALL_PATH=/var/opt
      - GROUP=praveen_group
      - --set-host-name=praveen_host
      - --set-host-tag=praveen_tag
      - --set-host-property=property1
      - --set-host-property=other=property
  tasks:
    - import_role:
        name: oneagent
