---
all:
  children:
    unix:
      children:
        linux:
          children:
            linux_other:
              hosts:
                52.208.181.26:
              vars:
                oneagent_installer_arch: x86
                oneagent_platform_install_args:
                  - USER=ansible
      vars:
        ansible_become: true
